version: '3.1'

services:
  client: 
    depends_on : 
      - mongo
    build:
      context: client/
      target: production
    ports:
      - 3001:3000
  server: 
    restart: always
    build:
      context: server/
      target: production
    environment:
      MONGO_URL: mongodb://root:root@mongo
    ports:
      - 3000:3000
    links: 
      - mongo
    networks:
      - node-webapp-network


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE : aedb
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    networks:
      - node-webapp-network
  
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user*22
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    links: 
      - mongo
    networks:
      - node-webapp-network
    

networks:
  node-webapp-network:
    driver: bridge
    
volumes:
  db_data:
